-- local null_ls = require("null-ls")
-- local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics
-- local completion = null_ls.builtins.completion
-- local sources = {
--   sources = {
--     -- Formatoes
--     -- formatting.autopep8,
--     -- formatting.isort,
--     formatting.json_tool,
--     formatting.stylua.with({
--       extra_args = { "--indent-type", "Tabs", "--indent-width", "2" },
--     }),
--     -- Dags
--     diagnostics.eslint_d,
--     -- diagnostics.mypy,
--     -- diagnostics.flake8,
--     diagnostics.pylint,
--     diagnostics.hadolint,
--     diagnostics.yamllint,
--     -- Completoes
--     completion.luasnip,
--   },
-- }
-- null_ls.setup({ sources = sources, update_in_insert = true })
